# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-11 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='place',
            new_name='detail_address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='is_deleted',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='tel',
            new_name='phone',
        ),
        migrations.AlterModelTable(
            name='address',
            table='tb_addresses',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
